version: '3'
services:
  cloud-eureka-server:
    container_name: cloud-eureka-server
    build:
      context: ./cloud-eureka/eureka-server/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"

  cloud-config-server:
    depends_on:
      - cloud-eureka-server
    container_name: cloud-config-server
    build:
      context: ./cloud-eureka/cloud-config-server/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8011:8011"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://cloud-eureka-server:8000/eureka

  gateway-server:
    depends_on:
      - cloud-config-server
    container_name: gateway-server
    build:
      context: ./cloud-eureka/gateway-server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8090:8090"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://cloud-eureka-server:8000/eureka

  login-register-service:
    depends_on:
      - cloud-config-server
    container_name: login-register-service
    build:
      context: ./account-manager/login-register-service
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://cloud-eureka-server:8000/eureka

  oauth2-security-service:
    depends_on:
      - cloud-config-server
    container_name: oauth2-security-service
    build:
      context: ./account-manager/oauth2-security-service
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://cloud-eureka-server:8000/eureka