# Application-wide properties
server:
  port: 8011

spring:
  application:
    name: cloud-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SevoMkrtchyan/aurora-cloud-config
          force-pull: true

#        native:
#          search-locations:
#            - classpath:/

management:
  endpoints:
    web:
      base-path: /admin


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}
      instance:
        preferIpAddress: true