# Application-wide properties
server:
  port: 8011

spring:
  application:
    name: cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}
      instance:
        preferIpAddress: true